[package]
name = "ledgerflow-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
flume.workspace = true
hpx = { workspace = true, features = ["json"] }
ledgerflow-core = { path = "../ledgerflow-core" }
ledgerflow-facilitator = { path = "../ledgerflow-facilitator" }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tracing.workspace = true
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower = { workspace = true, features = ["util"] }

[lints]
workspace = true
