[workspace]
members = [
    "ledgerflow-balancer",
    "ledgerflow-bot",
    "ledgerflow-cli",
    "ledgerflow-indexer",
    "ledgerflow-migrations",
]
resolver = "2"

[workspace.dependencies]
# Web framework
axum = "0.8.4"
tokio = "1.46.1"
tokio-test = "0.4.4"
tower-http = "0.6.6"

# Database
sqlx = "0.8.6"

# CLI
clap = "4.5.40"

# Configuration
config = "0.15.11"
serde = "1.0.219"
serde_json = "1.0.140"
serde_yaml = "0.9.33"

# Logging and tracing
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# Error handling
color-eyre = "0.6.5"
eyre = "0.6.12"
thiserror = "2.0.12"

# Utilities
chrono = "0.4.41"
uuid = "1.17.0"

# Crypto
hex = "0.4.3"
rand = "0.9.1"
sha3 = "0.10.8"

# Ethereum/EVM interaction
alloy = "1.0.19"

# Telegram Bot Framework
teloxide = "0.16.0"

# HTTP client
reqwest = "0.12.22"

# QR code generation
image = "0.25.6"
qrcode = "0.14.1"

# Base64 encoding
base64 = "0.22.1"
