# LedgerFlow Facilitator Configuration

# Server configuration
host = "0.0.0.0"
port = 3402

# Sui gRPC URLs
sui_testnet_grpc_url = "https://fullnode.testnet.sui.io:443"

# Transaction settings
gas_budget = 100_000_000

# Signing configuration
signer_type = "private-key"

# Private key will be read from environment variable SUI_PRIVATE_KEY
# Do not commit private keys to version control!
