//! WalletConnect v2 dApp client and [`WalletSigner`] adapter.
//!
//! [`WcV2Signer`] implements the [`WalletSigner`] capability interface over a
//! standard WalletConnect v2 session. It acts as the **dApp** side: it connects
//! to a WC v2 relay, pairs with a wallet (e.g. OneCipher) via a pairing URI,
//! establishes a session, and routes signing requests through the relay.
//!
//! The protocol layer is self-contained (no dependency on any specific wallet
//! implementation), preserving LedgerFlow's design red line of wallet
//! neutrality. The crypto follows the official `@walletconnect/utils`
//! reference implementation (X25519 + HKDF-SHA256 key agreement,
//! ChaCha20-Poly1305 envelopes).

mod crypto;
mod dapp;
mod jsonrpc;
#[cfg(test)]
mod mock_relay;
mod relay;
mod uri;

use std::sync::{Arc, OnceLock};

pub(crate) use dapp::WcDappClient;
use ledgerflow_core::{SignatureEnvelope, SignerRef, SigningAlgorithm};
pub(crate) use uri::PairingUri;

use crate::{
    error::WalletError,
    signer::{
        SignPaymentRequest, SignRequest, SignResult, SignedPayment, WalletDescriptor, WalletSigner,
    },
};

/// Configuration for a [`WcV2Signer`].
#[derive(Clone, Debug)]
pub struct WcV2Config {
    /// Relay WSS URL. Defaults to `wss://relay.walletconnect.com` when `None`.
    pub relay_url: Option<String>,
    /// dApp name advertised to the wallet during pairing.
    pub dapp_name: String,
    /// dApp URL advertised to the wallet during pairing.
    pub dapp_url: String,
}

impl Default for WcV2Config {
    fn default() -> Self {
        Self {
            relay_url: None,
            dapp_name: "LedgerFlow".to_string(),
            dapp_url: "https://ledgerflow.longcipher.com".to_string(),
        }
    }
}

/// A [`WalletSigner`] over a WalletConnect v2 session (dApp role).
///
/// Construct with [`WcV2Signer::connect`], passing a pairing URI generated by
/// the target wallet (e.g. `onecipher wc pair`). The session is established
/// synchronously; subsequent [`WalletSigner`] calls are routed over the relay.
///
/// # EVM semantics
///
/// WC v2 wallets expose EVM accounts, not raw public keys. Consequently:
/// - [`WalletSigner::keys`] returns the account address as the signer identifier (`public_key` =
///   20-byte address, `key_id` = hex address).
/// - [`WalletSigner::sign`] maps to `personal_sign` (EIP-191); the returned signature is a 65-byte
///   secp256k1 `(r ‖ s ‖ v)` value.
/// - [`WalletSigner::sign_payment`] builds a native EIP-1559 transfer and maps to
///   `eth_signTransaction` (signs without broadcasting).
pub struct WcV2Signer {
    client: Arc<WcDappClient>,
    descriptor: WalletDescriptor,
    config: WcV2Config,
}

impl std::fmt::Debug for WcV2Signer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WcV2Signer")
            .field("descriptor", &self.descriptor)
            .field("config", &self.config)
            .finish_non_exhaustive()
    }
}

impl WcV2Signer {
    /// Connects to a WC v2 relay, pairs with the wallet behind `pairing_uri`,
    /// and establishes a session.
    ///
    /// `pairing_uri` is a `wc:` URI (e.g. produced by `onecipher wc pair`).
    /// This call blocks until the wallet approves the session proposal.
    pub fn connect(pairing_uri: &str, config: WcV2Config) -> Result<Self, WalletError> {
        let runtime = wc_runtime()?;
        let parsed = PairingUri::parse(pairing_uri)?;
        let client = Arc::new(WcDappClient::new());
        runtime.block_on(async {
            client.connect(&parsed, config.relay_url.as_deref()).await?;
            client.propose(&config.dapp_name, &config.dapp_url).await?;
            Ok::<(), WalletError>(())
        })?;
        let descriptor = WalletDescriptor {
            name: "walletconnect".to_string(),
            algorithms: vec![
                SigningAlgorithm::Secp256k1,
                SigningAlgorithm::EthPersonalSign,
                SigningAlgorithm::EthTypedData,
            ],
            version: env!("CARGO_PKG_VERSION").to_string(),
        };
        Ok(Self { client, descriptor, config })
    }

    /// Closes the relay connection (best-effort).
    pub fn disconnect(&self) {
        let runtime = wc_runtime().ok();
        if let Some(runtime) = runtime {
            let client = Arc::clone(&self.client);
            runtime.block_on(async move {
                client.close().await;
            });
        }
    }

    /// Returns the first EVM account address (hex) from the session.
    fn account(&self) -> Result<String, WalletError> {
        let runtime = wc_runtime()?;
        let result = runtime.block_on(
            self.client.request(jsonrpc::method::ETH_REQUEST_ACCOUNTS, serde_json::json!([])),
        )?;
        let accounts = result.as_array().ok_or_else(|| {
            WalletError::InvalidPayload("eth_requestAccounts: expected array".to_string())
        })?;
        let account = accounts
            .first()
            .and_then(|a| a.as_str())
            .ok_or_else(|| WalletError::Rejected("wallet returned no accounts".to_string()))?;
        Ok(account.to_string())
    }
}

impl WalletSigner for WcV2Signer {
    fn descriptor(&self) -> WalletDescriptor {
        self.descriptor.clone()
    }

    fn sign(&self, request: &SignRequest) -> Result<SignResult, WalletError> {
        let runtime = wc_runtime()?;
        let account = self.account()?;
        let message_hex = format!("0x{}", hex::encode(&request.message));
        let params = serde_json::json!([message_hex, account]);
        let result =
            runtime.block_on(self.client.request(jsonrpc::method::PERSONAL_SIGN, params))?;
        let sig_hex = result.as_str().ok_or_else(|| {
            WalletError::InvalidPayload("personal_sign: expected string".to_string())
        })?;
        let sig_bytes = decode_hex(sig_hex)?;
        // Recover the actual compressed public key from the signature so the
        // returned signer reference supports strict verification
        // (EthPersonalSign recovers and compares against the claimed key).
        let recovered = ledgerflow_core::crypto::recover_public_key_from_personal_sign(
            &request.message,
            &sig_bytes,
        );
        // Fall back to the 20-byte address claim when recovery fails (the
        // address is still a valid signer reference for EthPersonalSign).
        let public_key = match recovered {
            Some(key) => key.to_vec(),
            None => decode_hex(&account)?,
        };
        Ok(SignResult {
            signer: SignerRef {
                alg: SigningAlgorithm::EthPersonalSign,
                public_key,
                key_id: Some(account),
            },
            signature: SignatureEnvelope {
                alg: SigningAlgorithm::EthPersonalSign,
                value: sig_bytes,
            },
        })
    }

    fn keys(&self) -> Result<Vec<SignerRef>, WalletError> {
        let account = self.account()?;
        Ok(vec![SignerRef {
            alg: SigningAlgorithm::Secp256k1,
            public_key: decode_hex(&account)?,
            key_id: Some(account),
        }])
    }

    fn sign_payment(&self, request: &SignPaymentRequest) -> Result<SignedPayment, WalletError> {
        let runtime = wc_runtime()?;
        let account = self.account()?;
        let tx = build_eip1559_tx(request, &account)?;
        let params = serde_json::json!([tx]);
        let result =
            runtime.block_on(self.client.request(jsonrpc::method::ETH_SIGN_TRANSACTION, params))?;
        let raw = result.as_str().ok_or_else(|| {
            WalletError::InvalidPayload("eth_signTransaction: expected string".to_string())
        })?;
        Ok(SignedPayment {
            signer: SignerRef {
                alg: SigningAlgorithm::Secp256k1,
                public_key: decode_hex(&account)?,
                key_id: Some(account),
            },
            raw_transaction: raw.to_string(),
            tx_hash: None,
        })
    }
}

/// Builds a minimal EIP-1559 transaction object for `eth_signTransaction`.
///
/// Supports native transfers (`slip44:60` assets) and ERC-20 transfers
/// (`erc20:<address>` assets). ERC-20 transfers encode the standard
/// `transfer(address,uint256)` calldata and target the token contract.
fn build_eip1559_tx(
    request: &SignPaymentRequest,
    from: &str,
) -> Result<serde_json::Value, WalletError> {
    let chain_id = request.chain_id.strip_prefix("eip155:").ok_or_else(|| {
        WalletError::Rejected(format!(
            "unsupported chain id '{}': only eip155 chains are supported",
            request.chain_id
        ))
    })?;
    let chain_id_u64: u64 = chain_id
        .parse()
        .map_err(|_| WalletError::Rejected(format!("invalid eip155 chain id: {chain_id}")))?;
    let nonce = request.nonce.as_deref().unwrap_or("0");

    // CAIP-19 asset id: `<chain>/<namespace>:<reference>`, e.g.
    // `eip155:8453/erc20:0x...` for ERC-20 or `eip155:8453/slip44:60` for native.
    let (to, value, data, gas) = match request.asset.split_once('/') {
        Some((_, asset_ref)) if asset_ref.starts_with("erc20:") => {
            let token = &asset_ref["erc20:".len()..];
            let calldata = erc20_transfer_calldata(&request.payee, request.amount)?;
            (
                token.to_string(),
                "0x0".to_string(),
                format!("0x{}", hex::encode(calldata)),
                "0x186a0", // 100_000 (ERC-20 transfer)
            )
        }
        _ => (
            request.payee.clone(),
            format!("0x{:x}", request.amount),
            "0x".to_string(),
            "0x5208", // 21000 (native transfer)
        ),
    };

    Ok(serde_json::json!({
        "type": "0x2",
        "chainId": format!("0x{chain_id_u64:x}"),
        "nonce": nonce,
        "maxPriorityFeePerGas": "0x3b9aca00", // 1 gwei
        "maxFeePerGas": "0x3b9aca00",         // 1 gwei
        "gas": gas,
        "to": to,
        "value": value,
        "data": data,
        "from": from,
    }))
}

/// Encodes the ERC-20 `transfer(address,uint256)` calldata.
///
/// Layout: `selector(4) ‖ address(32, left-padded) ‖ amount(32, big-endian)`.
fn erc20_transfer_calldata(to: &str, amount: u128) -> Result<Vec<u8>, WalletError> {
    let selector = &ledgerflow_core::crypto::keccak256(b"transfer(address,uint256)")[..4];
    let addr_bytes = decode_hex(to)?;
    if addr_bytes.len() != 20 {
        return Err(WalletError::Rejected(format!(
            "ERC-20 payee must be a 20-byte address, got {} bytes",
            addr_bytes.len()
        )));
    }
    let mut calldata = Vec::with_capacity(4 + 32 + 32);
    calldata.extend_from_slice(selector);
    calldata.extend_from_slice(&[0u8; 12]); // left-pad address to 32 bytes
    calldata.extend_from_slice(&addr_bytes);
    calldata.extend_from_slice(&[0u8; 16]); // left-pad u128 amount to 32 bytes
    calldata.extend_from_slice(&amount.to_be_bytes());
    Ok(calldata)
}

/// Decodes a hex string (with or without `0x` prefix) into bytes.
fn decode_hex(s: &str) -> Result<Vec<u8>, WalletError> {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    hex::decode(stripped)
        .map_err(|e| WalletError::InvalidPayload(format!("invalid hex '{s}': {e}")))
}

/// Process-wide current-thread tokio runtime bridging the synchronous
/// [`WalletSigner`] seam to the async WC v2 client.
///
/// Built lazily via [`OnceLock`] and reused for the lifetime of the process.
/// The relay connection is held inside the [`WcDappClient`] between calls, so
/// each `block_on` performs one request/response round-trip over the same
/// socket.
static WC_RUNTIME: OnceLock<tokio::runtime::Runtime> = OnceLock::new();

/// Returns the process-wide WC runtime, creating it on first use.
fn wc_runtime() -> Result<&'static tokio::runtime::Runtime, WalletError> {
    if let Some(runtime) = WC_RUNTIME.get() {
        return Ok(runtime);
    }
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| WalletError::Transport(format!("failed to build WC runtime: {e}")))?;
    let _ = WC_RUNTIME.set(runtime);
    WC_RUNTIME.get().ok_or_else(|| WalletError::Transport("WC runtime unavailable".to_string()))
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]
    use super::*;

    #[test]
    fn decode_hex_handles_prefix() {
        assert_eq!(decode_hex("0xdeadbeef").expect("decode"), vec![0xde, 0xad, 0xbe, 0xef]);
        assert_eq!(decode_hex("deadbeef").expect("decode"), vec![0xde, 0xad, 0xbe, 0xef]);
        assert!(decode_hex("0xzz").is_err());
    }

    #[test]
    fn build_eip1559_tx_native_transfer() {
        let req = SignPaymentRequest {
            chain_id: "eip155:8453".to_string(),
            asset: "eip155:8453/slip44:60".to_string(),
            amount: 1_000_000_000_000_000_000,
            payee: "0x1111111111111111111111111111111111111111".to_string(),
            nonce: Some("5".to_string()),
        };
        let tx =
            build_eip1559_tx(&req, "0x2222222222222222222222222222222222222222").expect("build");
        assert_eq!(tx["type"], "0x2");
        assert_eq!(tx["chainId"], "0x2105");
        assert_eq!(tx["nonce"], "5");
        assert_eq!(tx["to"], "0x1111111111111111111111111111111111111111");
        assert_eq!(tx["value"], "0xde0b6b3a7640000");
    }

    #[test]
    fn build_eip1559_tx_rejects_non_eip155_chain() {
        let req = SignPaymentRequest {
            chain_id: "solana:mainnet".to_string(),
            asset: "eip155:8453/slip44:60".to_string(),
            amount: 1,
            payee: "0x1111111111111111111111111111111111111111".to_string(),
            nonce: None,
        };
        assert!(build_eip1559_tx(&req, "0x2222222222222222222222222222222222222222").is_err());
    }

    #[test]
    fn build_eip1559_tx_erc20_transfer() {
        let req = SignPaymentRequest {
            chain_id: "eip155:8453".to_string(),
            asset: "eip155:8453/erc20:0x833589fcd6edb6e08f4c7c32d4f71b54bda02913".to_string(),
            amount: 1_000_000, // 1 USDC (6 decimals)
            payee: "0x1111111111111111111111111111111111111111".to_string(),
            nonce: Some("3".to_string()),
        };
        let tx =
            build_eip1559_tx(&req, "0x2222222222222222222222222222222222222222").expect("build");
        // to = token contract, value = 0, data = transfer(address,uint256)
        assert_eq!(tx["to"], "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913");
        assert_eq!(tx["value"], "0x0");
        assert_eq!(tx["gas"], "0x186a0");
        let data = tx["data"].as_str().expect("data");
        // selector a9059cbb + left-padded address + left-padded amount
        assert!(data.starts_with("0xa9059cbb"));
        assert!(data.ends_with("00000000000000000000000000000000000000000000000000000000000f4240"));
    }

    #[test]
    fn erc20_calldata_encodes_selector_address_amount() {
        let calldata =
            erc20_transfer_calldata("0x1111111111111111111111111111111111111111", 1_000_000)
                .expect("calldata");
        assert_eq!(calldata.len(), 4 + 32 + 32);
        assert_eq!(&calldata[..4], &[0xa9, 0x05, 0x9c, 0xbb]);
        // address is left-padded to 32 bytes
        assert_eq!(&calldata[4..16], &[0u8; 12]);
        assert_eq!(&calldata[16..36], &[0x11u8; 20]);
        // amount is left-padded to 32 bytes
        assert_eq!(&calldata[36..52], &[0u8; 16]);
        assert_eq!(&calldata[52..], &1_000_000u128.to_be_bytes());
    }

    #[test]
    fn erc20_calldata_rejects_bad_address() {
        assert!(erc20_transfer_calldata("0x1234", 1).is_err());
    }
}
