[package]
name = "ledgerflow_vault"
edition = "2024.beta"
version = "1.0.0"
license = "MIT"
authors = ["LedgerFlow Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
ledgerflow_vault = "0x0"
